services:
  core:
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - maven-cache:/root/.m2
    environment:
      - ACTIVE_PROFILE=dev
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - SPRING_DATA_REDIS_URL=redis://redis:6379

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  maven-cache:
  redis_data: