services:
  core:
    restart: unless-stopped
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - maven-cache:/root/.m2
    environment:
      - ACTIVE_PROFILE=prod
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_URL=${REDIS_URL}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  maven-cache: