server:
  port: ${PORT:8080}

spring:
  application:
    url: ${APP_URL:http://localhost:8080}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cache:
    type: REDIS

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
    web:
      pageable:
        max-page-size: 50

token:
  secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:issuer}

springdoc:
  writer-with-default-pretty-printer: true
  swagger-ui:
    syntaxHighlight:
      activated: true