spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password: dev
    title: "Twitter API"
    version: ${APP_VERSION:"x.x.x"}
    url: ${SERVER_URL:http://localhost:8080/}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

token:
  issuer: "${TOKEN_ISSUER:default_issuer}"
  secret: "${TOKEN_SECRET:default_secret}"